Add functions for getting quay repos and robot accounts
konflux-ci/image-controller pull request #19
Opened 2023-04-11 09:01 UTC by tnevrlka

Add GetAllRepositories and GetAllRobotAccounts functions to quay.go for use in https://github.com/redhat-appstudio/e2e-tests/pull/421.

2023-04-11 09:11 UTC, tkdchen approved these changes

2023-04-11 09:12 UTC, mmorhun requested changes
It will not get all repositories, you need to implement pagination.

2023-04-11 09:31 UTC, psturc commented on pkg/quay/quay.go
> +		fmt.Printf("error getting repositories, got status code %d", res.StatusCode)
should this message be added to the error returned below? (i.e. wrapped by `fmt.Errorf()`

and similarly in [the other method](https://github.com/redhat-appstudio/image-controller/pull/19/files#diff-d4a36e5f4e14c5636dfed4031b618cc2a45afc79934eabb0336a1adde773fd1bR334) as well

2023-04-12 07:54 UTC, mmorhun approved these changes
LGTM

2023-04-12 11:24 UTC, psturc reviewed
if there's some reasonable way to test the pagination, I'd add such test, otherwise lgtm

2023-04-13 11:16 UTC, merged